import { CSSProperties } from "react"

export const CSS_PROPERTIES = {
	"--title-font-family": '"ivypresto-display", serif',
	"--title-line-height": "116.3%",
	"--body-padding": "50px",
	"--padding": "var(--gap-2) var(--body-padding)",
	"--header-height": "80px",
	"--gap-1": "10px",
	"--gap-2": "20px",
	"--gap-3": "30px",
	"--gap-4": "50px",
	"--gap-5": "65px",
	"--section-max-width": "650px",
	"--paragraph-size-1": "1.6rem",
	"--paragraph-size-2": "1.8rem",
	"--paragraph-size-3": "2.2rem",
	"--title-1": "clamp(4rem, 10vw, 7rem)",
	"--title-2": "clamp(2.7rem, 10vw, 4.7rem)",
	"--title-3": "clamp(2.7rem, 10vw, 3.2rem)",
	"--line-height": "130%",
	"--form-element-radius": "12px",
	"--background-100": "#fff",
	"--background-200": "#fafbff",
	"--background-300": "#f7f9ff",
	"--background-400": "#f5f7ff",
	"--background-500": "#f2f4ff",
	"--background-600": "#f0f2ff",
	"--background-700": "#eef0ff",
	"--background-800": "#ecedef",
	"--background-900": "#eaecee",
	"--background-1000": "#e8e9ee",
	"--background-100-rgb": "255, 255, 255",
	"--foreground-100": "#000",
	"--foreground-200": "#303030",
	"--foreground-300": "#505050",
	"--foreground-400": "#707070",
	"--foreground-500": "#808080",
	"--foreground-600": "#909090",
	"--primary-100": "#FFD900",
	"--primary-200": "#ffde46",
	"--red": "#e83e15",
	"--red-100": "#FF0000",
	"--red-200": "#e83e15",
	"--green": "#084607",
	"--yellow": "#f6cc0f",
	"--error": "#a41900",
	"--a-color": "#0d3da4",
	"--outline": "2px solid rgba(30, 143, 255, 0.616)",
	"--gradient-1":
		"linear-gradient(90deg, var(--background-200) 0%, rgba(var(--background-100-rgb), 0.5) 100%)",
	"--default-transition": "400ms ease",
	"--light-border": "0.5px solid var(--background-1000)",
	"--light-border-on-primary": "0.5px solid var(--primary-200)",
	"--rotate": "rotate 1.5s linear infinite",
	"--rotate-2": "rotate-2 1.5s linear infinite",
	"--card-padding": "20px",
	"--card-radius": "15px",
	"--card-shadow": "0 0 10px rgba(0, 0, 0, 0.1)",
	"--inline-button-width": "55px",
	"--shake-animation": "shake 3s ease-in-out infinite",
}

export const globalStyles: CSSProperties = {
	fontFamily: "Roboto, Arial, Helvetica, sans-serif",
	margin: 0,
	padding: 0,
	boxSizing: "border-box",
}

export const selectorStyles: [string, CSSProperties][] = [
	[
		"b, a, i",
		{
			fontSize: "inherit",
			fontFamily: "inherit",
		},
	],
	["div, tr, td, table, tbody, body, html", globalStyles],
	[
		"table",
		{
			borderCollapse: "separate",
			borderSpacing: "0 var(--gap-1)",
			maxWidth: "600px",
		},
	],
]

export enum ComponentTypes {
	Paragraph = "Paragraph",
	Heading = "Heading",
	HeadingTwo = "HeadingTwo",
	HeadingThree = "HeadingThree",
	HeadingFour = "HeadingFour",
	HeadingFive = "HeadingFive",
	HeadingSix = "HeadingSix",
	Button = "Button",
	Image = "Image",
	Line = "Line",
	Spacing = "Spacing",
	TrackingPixel = "TrackingPixel",
	Unsubscribe = "Unsubscribe",
}
