steps:
    - name: "gcr.io/cloud-builders/docker"
      args:
          [
              "build",
              "-t",
              "us-central1-docker.pkg.dev/dentalreviewsync/api/reviewsurplus-gcloud-api",
              ".",
          ]

    - name: "gcr.io/cloud-builders/docker"
      args:
          [
              "push",
              "us-central1-docker.pkg.dev/dentalreviewsync/api/reviewsurplus-gcloud-api",
          ]
